provider "aws" {
  region = "sa-east-1" # Substitua pela sua região AWS
}
 
resource "aws_db_instance" "rds_instance" {
  address                               = "chargeback.coid1xsnbqhf.sa-east-1.rds.amazonaws.com"
    allocated_storage                     = 100
    arn                                   = "arn:aws:rds:sa-east-1:360706934225:db:chargeback"
    auto_minor_version_upgrade            = false
    availability_zone                     = "sa-east-1a"
    backup_retention_period               = 7
    backup_target                         = "region"
    backup_window                         = "00:00-04:00"
    ca_cert_identifier                    = "rds-ca-rsa2048-g1"
    character_set_name                    = null
    copy_tags_to_snapshot                 = true
    custom_iam_instance_profile           = null
    customer_owned_ip_enabled             = false
    db_name                               = "chargeback"
    db_subnet_group_name                  = "db-pagseguro-subnetgroup"
    dedicated_log_volume                  = false
    delete_automated_backups              = true
    deletion_protection                   = false
    domain                                = null
    domain_auth_secret_arn                = null
    domain_dns_ips                        = []
    domain_fqdn                           = null
    domain_iam_role_name                  = null
    domain_ou                             = null
    enabled_cloudwatch_logs_exports       = [
        "postgresql",
        "upgrade",
    ]
    endpoint                              = "chargeback.coid1xsnbqhf.sa-east-1.rds.amazonaws.com:5432"
    engine                                = "postgres"
    engine_lifecycle_support              = "open-source-rds-extended-support"
    engine_version                        = "14.11"
    engine_version_actual                 = "14.11"
    hosted_zone_id                        = "ZLRUIUX7Z3ZF7"
    iam_database_authentication_enabled   = false
    id                                    = "db-JXAUM6SZ2R4LJQ5IWXKGJVFRKE"
    identifier                            = "chargeback"
    identifier_prefix                     = null
    instance_class                        = "db.t3.small"
    iops                                  = 0
    kms_key_id                            = null
    latest_restorable_time                = "2024-12-06T19:24:33Z"
    license_model                         = "postgresql-license"
    listener_endpoint                     = []
    maintenance_window                    = "mon:05:00-mon:07:30"
    master_user_secret                    = []
    max_allocated_storage                 = 10000
    monitoring_interval                   = 0
    monitoring_role_arn                   = null
    multi_az                              = true
    nchar_character_set_name              = null
    network_type                          = "IPV4"
    option_group_name                     = "default:postgres-14"
    parameter_group_name                  = "db-chargeback-postgres-14"
    performance_insights_enabled          = true
    performance_insights_kms_key_id       = "arn:aws:kms:sa-east-1:360706934225:key/2716fac6-bdb6-4fdb-a526-b4e8e1b7a23c"
    performance_insights_retention_period = 7
    port                                  = 5432
    publicly_accessible                   = false
    replica_mode                          = null
    replicas                              = []
    replicate_source_db                   = null
    resource_id                           = "db-JXAUM6SZ2R4LJQ5IWXKGJVFRKE"
    skip_final_snapshot                   = true
    status                                = "available"
    storage_encrypted                     = false
    storage_throughput                    = 0
    storage_type                          = "gp2"
    tags                                  = {
        "ApplicationRole"        = "Banco de Dados"
        "BusinessUnit"           = "pagamentos"
        "CC"                     = "12188"
        "CriticalLevel"          = "4"
        "Domain"                 = "chargeback"
        "EC"                     = "madripoor"
        "Email"                  = "l-dev-pagseguro-toronto@uolinc.com"
        "IsANBIMA"               = "false"
        "IsBACEN"                = "false"
        "IsBankingSecrecy"       = "false"
        "IsGDPR"                 = "false"
        "IsLGPD"                 = "false"
        "IsNotSecurityApply"     = "true"
        "IsPCI"                  = "false"
        "IsPII"                  = "false"
        "IsSOX"                  = "false"
        "IsStrategicFinancial"   = "false"
        "IsStrategicOperational" = "false"
        "Launched"               = "Condado"
        "Name"                   = "chargeback"
        "Product"                = "ADQUIRENCIA"
        "ReliabilityEngineer"    = "madripoor"
        "Slack"                  = "toronto-hall"
        "Team"                   = "Toronto"
        "Time"                   = "Melbourne"
        "TopDomain"              = "psp"
        "complianceList"         = "None"
        "complianceRequired"     = "False"
        "escalationList"         = "Mario Chaves de Lima Filho mclima@uolinc.com"
        "filaIM"                 = "scrum ama"
    }
    tags_all                              = {
        "ApplicationRole"        = "Banco de Dados"
        "BusinessUnit"           = "pagamentos"
        "CC"                     = "12188"
        "CriticalLevel"          = "4"
        "Domain"                 = "chargeback"
        "EC"                     = "madripoor"
        "Email"                  = "l-dev-pagseguro-toronto@uolinc.com"
        "IsANBIMA"               = "false"
        "IsBACEN"                = "false"
        "IsBankingSecrecy"       = "false"
        "IsGDPR"                 = "false"
        "IsLGPD"                 = "false"
        "IsNotSecurityApply"     = "true"
        "IsPCI"                  = "false"
        "IsPII"                  = "false"
        "IsSOX"                  = "false"
        "IsStrategicFinancial"   = "false"
        "IsStrategicOperational" = "false"
        "Launched"               = "Condado"
        "Name"                   = "chargeback"
        "Product"                = "ADQUIRENCIA"
        "ReliabilityEngineer"    = "madripoor"
        "Slack"                  = "toronto-hall"
        "Team"                   = "Toronto"
        "Time"                   = "Melbourne"
        "TopDomain"              = "psp"
        "complianceList"         = "None"
        "complianceRequired"     = "False"
        "escalationList"         = "Mario Chaves de Lima Filho mclima@uolinc.com"
        "filaIM"                 = "scrum ama"
    }
    timezone                              = null
    username                              = "dba"
    vpc_security_group_ids                = [
        "sg-80941ce6",
    ]
}